### ISSUE TITLE
Take ownership of my repo?

### ISSUE THREAD

**Issue by alexkalderimis** [intermine/intermine-ws-python#1]
I had an issue created against my repo since to the naive outsider it appears to be the main one. Would you like to take ownership of it (after merging back your progress of course)?

**Comment by julie-sullivan** [comment]
See https://github.com/alexkalderimis/intermine-ws-client.py/pull/6/

**Comment by nupurgunwant** [comment]
There are two ways to go about this, as far as I read:

1. We contact github to switch intermine/intermine-ws-python from forked mode to normal mode. Then alexkalderimis/intermine-ws-client.py can be deleted safely, if you wish to do so.
OR
2. The only way to do it ourselves is by destroying and recreating( pushing ) intermine/intermine-ws-python. But this way all the tickets will be deleted, so I think its not a good way.

**Comment by julie-sullivan** [comment]
Our repo is now detached!
