### ISSUE TITLE
Update of Documentation

### ISSUE THREAD

**Issue by nupurgunwant** [intermine/intermine-ws-python#16]
At present we have the docs hosted via pydocs, which will be in html files in a separate folder named 'docs' after the merge of #15. 

Originally, the documentation was hosted [here](https://pythonhosted.org/intermine/intermine-module.html) but it hasn't been updated with the current registry update. This is because the documentation aspect of pypi is undergoing some changes and doesn't allow updation of documentation at present. Refer to https://github.com/pypa/warehouse/issues/582 . 

As soon as this gets fixed, pypi can again be used as a way to keep the documentation.

**Comment by yochannah** [comment]
the warehouse no longer hosts docs; we're hosting them on gh-pages instead.
