### ISSUE TITLE
Make reviewing Pull Requests easier

### ISSUE THREAD

**Issue by nupurgunwant** [intermine/intermine-ws-python#2]
Pep8speaks is a GitHub app that automatically review Python code style over Pull Requests. 
The configuration is quite simple, and it can be used to review all the Python files.
Here is the repository: https://github.com/OrkoHunter/pep8speaks , for more information.

**Comment by julie-sullivan** [comment]
I see the comment from `pep8speaks` - that's great! Is this going to happen for all pull requests? Or just yours?
