### ISSUE TITLE
Update docs to indicate correct row formats available

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine-ws-python#3]
I was messing about with [pandas](https://pandas.pydata.org/) and [plotly](https://plot.ly/) for fun at a study group and I thought I'd pull in some familiar data into a data frame. I wanted to get the results in a raw-ish format, so I delved into the massive tutorial-in-comments in [query.py](https://github.com/intermine/intermine-ws-python/blob/201b8b1dc10cc2f1555c4f8845ea0960908bbb48/intermine/query.py) and thought I'd found what I wanted: a nice way to get the results as a simple string rather than an iterator, based on this comment here:  

https://github.com/intermine/intermine-ws-python/blob/201b8b1dc10cc2f1555c4f8845ea0960908bbb48/intermine/query.py#L262

```
         for row in query.result("string")
             print(row)
```

I think it was a trick, though! `query.result("whatever")` isn't a method and `query.results("whatever")` (note the additional **s**) IS a method but string isn't a valid arg. 

Maybe we just need to remove that line ;)

**Comment by nupurgunwant** [comment]
Hi @yochannah , you are right. The argument of `query.results` [and not `query.result`] needs to be a valid row format which constitutes of ['json', 'count', 'rr', 'tsv', 'jsonobjects', 'jsonrows', 'list', 'dict', 'csv'].
These are the formats in which the results can be presented. 

So, I think we should clearly specify in the comments that these are the row formats available for the user.
