### ISSUE TITLE
Syntax error when trying to apply a few constraints on a template

### ISSUE THREAD

**Issue by danielabutano** [intermine/intermine-ws-python#33]
It seems like when applying multiple options to one constraint, they need not be all enclosed by quotes (i.e. outside the sq. brackets), as when I removed that the error stopped showing.

**Comment by julie-sullivan** [comment]
@danielabutano Do you have the script you ran? or an example? We might need some specifics to be able to fix this.

**Comment by julie-sullivan** [comment]
Is this related to: https://github.com/intermine/intermine/issues/1981

**Comment by danielabutano** [comment]
@julie-sullivan yes it's the same issue in https://github.com/intermine/intermine/issues/1981 but in different repos. hard to find it. I will close it
