### ISSUE TITLE
List upload: don't create empty lists

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine-ws-python#34]
The InterMine python client allows users to create lists of things (e.g. lists of genes). If the list size is zero, the list should not be created.

See https://mybinder.org/v2/gh/intermine/intermine-ws-python-docs/master?filepath=09-tutorial.ipynb for more info on the process to create a list, or look at the full set of tutorials here: https://github.com/intermine/intermine-ws-python-docs.

If someone uses intermine-ws-python to try to create a list with 0 items, we should prevent this and give them a sensible clear error, e.g. "Lists must have one or more elements - the current list has 0".

**Comment by Sanat-Mishra** [comment]
Hey, can I try to resolve this issue?

**Comment by julie-sullivan** [comment]
Sure! It's quite possible that the problem is on the InterMine end and not the Python client. But it would be good to know either way. :)

**Comment by yochannah** [comment]
@Sanat-Mishra are you still interested in this issue? It's 100% fine if not - I'll add some more details and label it hacktoberfest if so :) 

(I reckon that even if the InterMine server is accepting empty lists when it shouldn't be, it makes sense for the python client to give a polite error rather than passing it on to the InterMine server to deal with... )

**Comment by Sanat-Mishra** [comment]
@yochannah please go ahead! I'm sorry for letting this hang until now. :/

**Comment by yochannah** [comment]
@Sanat-Mishra no need to apologise at all! :)

**Comment by yochannah** [comment]
Okay, I've added the hacktoberfest label to this issue - contributors are welcome! 

## if you want to pick up this task

0. Take a look at the [InterMine contributing guidelines](http://intermine.org/contributing/)
1. Comment on this issue stating that you intend to work on the task
2. When you're ready, add your work to the repo and create a pull request.
### What to do if you need help

Mention @yochannah, tweet [@yoyehudi](http://www.twitter.com/yoyehudi), pop by to say hi on [chat](http://chat.intermine.org) or if needed email yo@intermine.org. Don't forget we're usually only available during uk office hours and will not be able to respond at other times :)

**Comment by mbasil09** [comment]
I want to solve this issue.
Do you want to terminate the program and just print a polite message, or do you want to ask the user once again to enter a new list?

**Comment by yochannah** [comment]
Hey @mbasil09, thanks for picking this up! cancel the operation and print a polite message would be perrrfect :)

**Comment by mbasil09** [comment]
@yochannah 
I think this is solved, you may close this.

**Comment by yochannah** [comment]
so it did!

**Comment by yochannah** [comment]
@mbasil09 one small handy tip - when you make a commit, you can use phrases like "closes #34" or "fix #34" and then when the PR is merged, the issue will auto close - this is a nifty little github feature that can be really handy :) 

more info: https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords
