### ISSUE TITLE
Go right from query results to a data frame

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine-ws-python#39]
Right now when we return query results, they're returned as in iterator. If you wish to work with query results in a dataframe, you have to manually build the dataframe step by step in a for loop, which can be a pain. 

We should add a backwards-compatible way of getting query results in a dataframe - so our old tutorials and code should still work, but perhaps add another argument or use different methods to fetch the results as a dataframe.

Presumably this will make us require pandas by default. 

We have a tutorial here that shows how to handle intermine query data: https://mybinder.org/v2/gh/intermine/intermine-ws-python-docs/master?filepath=02-tutorial.ipynb and generally there is more info in out other tutorials as well: (scroll down and look at the list of tutorials in the readme https://github.com/intermine/intermine-ws-python-docs/ )

**Comment by yochannah** [comment]
I've added the hacktoberfest label to this issue and expanded the description. Contributions are extremely welcome! 

## if you want to pick up this task

0. Take a look at the [InterMine contributing guidelines](http://intermine.org/contributing/)
1. Comment on this issue stating that you intend to work on the task
2. When you're ready, add your work to the repo and create a pull request.

### What to do if you need help

Mention @yochannah, tweet [@yoyehudi](http://www.twitter.com/yoyehudi), pop by to say hi on [chat](http://chat.intermine.org) or if needed email yo@intermine.org. Don't forget we're usually only available during uk office hours and will not be able to respond at other times :)

**Comment by mbasil09** [comment]
@julie-sullivan @yochannah 
I would like to do this.
Do I need to return the dataframe or simply print it?
I think returning it would be better as you could perform various other operations on it.

**Comment by yochannah** [comment]
@mbasil09 please give this a go! 

returning sounds a lot more useful than printing, I think - nice point! 👍
