### ISSUE TITLE
What happened to the API docs?

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine-ws-python#4]
There is a link on [intermine.readthedocs.io](http://intermine.readthedocs.io/en/latest/web-services/#api-and-client-libraries) to https://pythonhosted.org/intermine/ but this presents just several pages with empty frames.

**Comment by nupurgunwant** [comment]
This link was working fine the last time I checked. I guess this is the correct link now:
[https://pythonhosted.org/intermine/intermine-module.html](url)

**Comment by nupurgunwant** [comment]
I did all necessary steps to upload intermine on pypi (as I mentioned below) and can even install it now. 

**Steps to upload on pypi**

Reference: https://packaging.python.org/tutorials/packaging-projects/
Download the master branch, name it intermine
$cd intermine
$python3 -m pip install --user --upgrade setuptools wheel
$python3 setup.py sdist bdist_wheel
This is created : 
dist/
  example_pkg-0.0.1-py3-none-any.whl
  example_pkg-0.0.1.tar.gz

$python3 -m pip install --user --upgrade twine
$twine upload --repository-url https://test.pypi.org/legacy/ dist/*

**To check:**
$python3 -m pip install --index-url https://test.pypi.org/simple/ intermine

However, I am unable to view any change here https://pythonhosted.org/intermine/intermine-module.html . Any ideas why?

**Comment by nupurgunwant** [comment]
For the time being, pydoc can be used hosting documentation, this way
```
nupurgunwant@Nupurs-MacBook-Pro ~ $ pydoc -w intermine.constraints
wrote intermine.constraints.html
nupurgunwant@Nupurs-MacBook-Pro ~ $ open ./intermine.constraints.html
```
Similarly, it can be done for all the files ie intermine.query, intermine.registry etc

**Comment by julie-sullivan** [comment]
@yochannah what do you think? I am loathe to put the API docs somewhere temporarily.

**Comment by yochannah** [comment]
I really, really don't want to go into a tutorial without proper API docs. We've said it's beginner friendly, and expecting someone to generate docs on the command line rather than read a web page doesn't quite fit the "beginner" slot. 

If I host a copy of the docs on my own github account and promise to convert them to a redirect when the pypi docs are working again, would that satisfy?

**Comment by nupurgunwant** [comment]
I can surely put the html format files on github. Does that suffice?

**Comment by yochannah** [comment]
that would solve my use case!

**Comment by nupurgunwant** [comment]
@yochannah Added. I hope this helps

**Comment by yochannah** [comment]
Whew, I've copied it to the gh-pages branch. http://intermine.org/intermine-ws-python
