### ISSUE TITLE
calling `service.get_template()` triggers an error in Python 3.7

### ISSUE THREAD

**Issue by fomightez** [intermine/intermine-ws-python#40]
Executing `service.get_template()` in Python 3.7 results in `RuntimeError: generator raised StopIteration`. The example is below is when accessing FlyMine; however, I have seen the same thing happens for YeastMine.
Demonstrating the issue:
Go to [here](https://github.com/intermine/intermine-ws-python-docs) and scroll fown to the 'Tutorial 7: Templates' section. Under there click the `launch binder` badge and try running the first cell after the session spins up. The error will come up. as currently the Binder instances are defaulting to Python 3.7.

Example output from the demonstration:
![stopiteration_ error_with_template_example](https://user-images.githubusercontent.com/4700990/58340001-cde28480-7e18-11e9-9f92-f786984237eb.png)

I suspect it is related to the second item under 'Changes in Python Behavior' [here](https://docs.python.org/3.7/whatsnew/3.7.html#changes-in-python-behavior) as currently the Binder instances are defaulting to Python 3.7.. A possible fix to a related issue is shown [here](https://stackoverflow.com/a/51701040/8508004). It looks like incorporating that approach to line 477 of `intermine/query.py` may fix it.

**Comment by yochannah** [comment]
@fomightez - thanks for reporting this! I've submitted a PR that hopefully will fix the issue, but until it's deployed, there is a workaround for binder - specifying python 3.5 in runtime.txt. 

https://github.com/yochannah/intermine-ws-python-docs/blob/template-error/runtime.txt

**Comment by jburel** [comment]
The problem still persists. Tested with Python 3.7.10

**Comment by hiyama341** [comment]
Problem also present with python version : 3.8.11. Anyone found a workaround the problem?

**Comment by jburel** [comment]
Note that I cannot use Python 3.5 (as suggested workaround above) since I am using other dependencies requiring Python 3.7+

**Comment by jburel** [comment]
Thanks for info.
Using the dev version is an option but for publishing workflow using intermine is not ideal.
Is there any change to have a newer working version pushed to pypi and conda (I am using the conda channel)?
Thanks

**Comment by yochannah** [comment]
Hmmm - I no longer work at InterMine but I'll just namedrop @leoank and @uosl just to make sure current InterMine staff see this issue is still open...

**Comment by uosl** [comment]
Thanks for bringing this to our attention. We have our hands full at the moment, but hopefully later this week we'll look at making another release.

**Comment by danielabutano** [comment]
@jburel we have just release 1.12.0

**Comment by jburel** [comment]
Thanks @danielabutano I will give it a try
