### ISSUE TITLE
Add an easy way to print a list

### ISSUE THREAD

**Issue by intermineorg** [intermine/intermine-ws-python#41]
People want to view the list contents. I don't see an easy way to do that.

**Comment by yochannah** [comment]
Yes please.

**Comment by yochannah** [comment]
fixed as part of #47. 

@arun-y99 - you've made some awesome contributions to this repo. If you'd like me to pop some InterMine stickers in the mail, email me on yo@intermine.org to tell me your mailing address! 📮
