### ISSUE TITLE
[documentation update - easy task] easy_install is deprecated - remove from readme instructions

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine-ws-python#45]
let's tell people to use bioconda or pip instead of easy_install.

Deprecation notice: https://setuptools.readthedocs.io/en/latest/easy_install.html

## if you want to pick up this task

0. Take a look at the [InterMine contributing guidelines](http://intermine.org/contributing/)
1. Comment on this issue stating that you intend to work on the task
2. When you're ready, add your work to the repo and create a pull request.

### What to do if you need help

Mention @yochannah, tweet [@yoyehudi](http://www.twitter.com/yoyehudi), pop by to say hi on [chat](http://chat.intermine.org) or if needed email yo@intermine.org. Don't forget we're usually only available during uk office hours and will not be able to respond at other times :)

**Comment by Sanat-Mishra** [comment]
Hey! Can I take this up? :)

**Comment by yochannah** [comment]
@Sanat-Mishra go for it!

**Comment by yochannah** [comment]
Fixed by #57 💯
