### ISSUE TITLE
[easy task] Create getVersion function to return the version of a given InterMine

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine-ws-python#49]
We have a method, `getInfo`, that fetches the version of a given InterMine from the registry here: https://github.com/intermine/intermine-ws-python/blob/dev/intermine/registry.py#L11 

getInfo method only prints results to the screen. I would be nice to have a similar method called `getVersion` that returns the result (rather than printing) so it can be used programmatically, and without the extra bits printed to the screen. 

Labelled as easy since much of this method can be copied from `getInfo`. 

Ideally the return response should contain keys for the following three version options:

```
API Version: 25
Release Version: 45.1 2017 August
InterMine Version: 1.8.5
```

## if you want to pick up this task

0. Take a look at the [InterMine contributing guidelines](http://intermine.org/contributing/)
1. Comment on this issue stating that you intend to work on the task
2. When you're ready, add your work to the repo and create a pull request.

### What to do if you need help

Mention @yochannah, tweet [@yoyehudi](http://www.twitter.com/yoyehudi), pop by to say hi on [chat](http://chat.intermine.org) or if needed email yo@intermine.org. Don't forget we're usually only available during uk office hours and will not be able to respond at other times :)

**Comment by TheAntiSnipe** [comment]
Hi! I'd like to work on this issue.

**Comment by yochannah** [comment]
Fixed by https://github.com/intermine/intermine-ws-python/pull/50
