### ISSUE TITLE
Set up autopep8 as a task and add guidelines to the readme

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine-ws-python#51]
Since we have the pep8speaks bot commenting on our issues, we ought to make it easy for people to format things in a way that makes pep8 happy. This project looks like it would do it: https://pypi.org/project/autopep8/

### task
- add autopep8 to requirements.txt
- add instructions to the readme file telling people how to run it before making PRs. 

## if you want to pick up this task

0. Take a look at the [InterMine contributing guidelines](http://intermine.org/contributing/)
1. Comment on this issue stating that you intend to work on the task
2. When you're ready, add your work to the repo and create a pull request.
### What to do if you need help

Mention @yochannah, tweet [@yoyehudi](http://www.twitter.com/yoyehudi), pop by to say hi on [chat](http://chat.intermine.org) or if needed email yo@intermine.org. Don't forget we're usually only available during uk office hours and will not be able to respond at other times :)

**Comment by barhenkro** [comment]
Hi
I would like to work on this task

**Comment by yochannah** [comment]
@barhenkro fantastic - please go ahead, and let us know if you have any questions! :)

**Comment by yochannah** [comment]
fixed by #52 - thank you so much @barhenkro !
