### ISSUE TITLE
travis ci build - upgrade pypy version to be 2.9 or greater

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine-ws-python#53]
Our travis ci build is failing on the two pypy settings because the default version of pypy for trusty is too old - it's 2.8 and needs to be at least 2.9.x in order to install pandas correctly. See https://travis-ci.org/intermine/intermine-ws-python/jobs/580760283 for an example of the failure. 

This is a link of different python and pypy versions: https://github.com/travis-ci/docs-travis-ci-com/pull/1249#issuecomment-307741238 

To test this, you could enable travis ci for your fork of this repo, or create a WIP (work in progress) PR - either is fine. 

## if you want to pick up this task

0. Take a look at the [InterMine contributing guidelines](http://intermine.org/contributing/)
1. Comment on this issue stating that you intend to work on the task
2. When you're ready, add your work to the repo and create a pull request.
### What to do if you need help

Mention @yochannah, tweet [@yoyehudi](http://www.twitter.com/yoyehudi), pop by to say hi on [chat](http://chat.intermine.org) or if needed email yo@intermine.org. Don't forget we're usually only available during uk office hours and will not be able to respond at other times :)

**Comment by yochannah** [comment]
quick additional note - if we can't get pypy 2.7 working it is probably not the end of the world, as 2.7 support is discontinued from the end of this year.

**Comment by KVGarg** [comment]
@yochannah Can't we go for xenial linux distri. on travis?

**Comment by yochannah** [comment]
@KVGarg that's another option, but then it requires a nontrivial script upgrade as the current script expects Java 8 (which isn't easy to install on xenial)

**Comment by yochannah** [comment]
for now I have removed pypy and I'll create an issue to add it back when we can upgrade our build machine distro. This is dependent on https://github.com/intermine/intermine/issues/2127
