### ISSUE TITLE
Issue with function query_to_barchart_log in interrmine/bar_chart.py

### ISSUE THREAD

**Issue by niveditarufus** [intermine/intermine-ws-python#71]
`---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-4-ea8f991734d6> in <module>
----> 1 b.query_to_barchart_log('<query model="genomic" view="Gene.name Gene.symbol Gene.length" sortOrder="Gene.name ASC" ><constraint path="Gene.length" op="&lt;" value="450074" /><constraint path="Gene.name" op="=" value="translation initiation factor IF-2-like" /></query>','true')
~/virtualenv/python3.5.6/lib/python3.5/site-packages/intermine/bar_chart.py in query_to_barchart_log(xml, resp)
    237     ax = y.plot(kind='bar')
    238     ax.set_title(list[0][0])
--> 239     ax.set_xlabel(l[1])
    240     if resp == 'true':
    241         ax.set_ylabel('log(' + l[2] + ')')
NameError: name 'l' is not defined
NameError: name 'l' is not defined`

**Comment by yochannah** [comment]
@niveditarufus what's the best way to test this fix?

**Comment by yochannah** [comment]
never mind, I figured it out and merged! 💯
